# Generated by Django 3.2.2 on 2021-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=40)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('keyword', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=264)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=264, null=True)),
                ('smptserver', models.CharField(blank=True, max_length=264, null=True)),
                ('smptemail', models.EmailField(blank=True, max_length=264, null=True)),
                ('smptpassword', models.CharField(blank=True, max_length=264)),
                ('smptport', models.CharField(blank=True, max_length=264)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon')),
                ('facebook', models.CharField(blank=True, max_length=264)),
                ('twitter', models.CharField(blank=True, max_length=264)),
                ('instagram', models.CharField(blank=True, max_length=264)),
                ('linkedin', models.CharField(blank=True, max_length=264)),
                ('contact', models.TextField()),
                ('reference', models.TextField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
