# Generated by Django 3.2.2 on 2021-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='details',
            field=models.TextField(default='fs'),
            preserve_default=False,
        ),
    ]
